### ISSUE TITLE
沃游戏线路有ios版本的软件么

### ISSUE THREAD

**Issue by branchGit** [simo8102/chinaunicom-AutoSignMachine#203]
沃游戏线路有ios版本的软件么

**Comment by simo8102** [comment]
有的哦

**Comment by branchGit** [comment]
> 有的哦

大佬，是哪个软件，我这搜不到啊，需要其他地区的id？

**Comment by asciichn** [comment]
同问

**Comment by simo8102** [comment]
> > 有的哦
> 
> 大佬，是哪个软件，我这搜不到啊，需要其他地区的id？

除了国区软件名和安卓版一样

**Comment by branchGit** [comment]
> > > 有的哦
> > 
> > 
> > 大佬，是哪个软件，我这搜不到啊，需要其他地区的id？
> 
> 除了国区软件名和安卓版一样

好的，谢谢大佬

**Comment by lingxi1322** [comment]
我怎么搜不到啊

**Comment by branchGit** [comment]
> > > 有的哦
> > 
> > 
> > 大佬，是哪个软件，我这搜不到啊，需要其他地区的id？
> 
> 除了国区软件名和安卓版一样

用了国外的id商店里搜这个名字没有。。。
