### ISSUE TITLE
【建议】去掉花费50积分抽奖

### ISSUE THREAD

**Issue by fxxf1111** [simo8102/chinaunicom-AutoSignMachine#224]
建议内容：

    在广东地区，很多人就是奔着定向积分来的，它可以用来参加抽奖活动，很有用。

    建议把这个任务注释掉。根本抽不中有用的东西。

**Comment by a753005179** [comment]
直接注释掉就行了
chinaunicom-AutoSignMachine/commands/tasks/unicom/unicom.js 
44-46行加//
